# Generated by Django 4.0.3 on 2022-05-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excuse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
